name: XaCore
version: '${project.version}'
main: me.xap3y.xacore.Main
api-version: '1.20'
author: xap3y

soft-depend: [PlaceholderAPI, Vault]

permissions:
    xacore.bypass:
        description: Bypass disabled commands
        default: op